export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

export const TOGGLE_COMMENT_APPROVED_REQUEST =
  'TOGGLE_COMMENT_APPROVED_REQUEST';
export const TOGGLE_COMMENT_APPROVED_SUCCESS =
  'TOGGLE_COMMENT_APPROVED_SUCCESS';
export const TOGGLE_COMMENT_APPROVED_FAIL = 'TOGGLE_COMMENT_APPROVED_FAIL';

export const GET_COMMENTS_BY_POST_REQUEST = 'GET_COMMENTS_BY_POST_REQUEST';
export const GET_COMMENTS_BY_POST_SUCCESS = 'GET_COMMENTS_BY_POST_SUCCESS';
export const GET_COMMENTS_BY_POST_FAIL = 'GET_COMMENTS_BY_POST_FAIL';

export const GET_ALL_COMMENTS_REQUEST = 'GET_ALL_COMMENTS_REQUEST';
export const GET_ALL_COMMENTS_SUCCESS = 'GET_ALL_COMMENTS_SUCCESS';
export const GET_ALL_COMMENTS_FAIL = 'GET_ALL_COMMENTS_FAIL';
